getwd()
setwd("E:/U/viruskillersRound2")
data3<-read.csv("train_zhang2.csv",as.is = TRUE,encoding="utf-8")
data3
lm.sales<-lm(y~x1+x2+x3+x4+x5+x6+x7+x8+x9+x10+x11+x12+x13+x14+x15+x16+x17+x18+x19+x20+x21,data=data3)
summary(lm.sales)
lm.step<-step(lm.sales,direction="both")
summary(lm.step)
y.res<-residuals(lm.sales)
y.rst<-rstandard(lm.step)
y.res
y.rst
y.fit<-predict(lm.step)
plot(y.res~y.fit)
plot(y.rst~y.fit)
lm.stepnew<-update(lm.step,log(.)~.)
y.rst2<-rstandard(lm.stepnew)
y.fit2<-predict(lm.stepnew)
plot(y.rst2~y.fit2)
lm.sales3<-lm(log(y)~x1+x2+x3+x4+x5+x6+x7+x8+x9+x10+x11+x12+x13+x14+x15+x16+x17+x18+x19+x20+x21,data=data3[-c(3,12,151),])
lm.step3<-step(lm.sales3,direction="both")
summary(lm.step3)
y.fit3<-predict(lm.step3)
y.rst3<-rstandard(lm.step3)
plot(y.rst3~y.fit3)
par(mfrow=c(2,2))
plot(lm.stepnew)
influence.measures(lm.stepnew)
preds<-read.csv("test_zhang2.csv",as.is = TRUE,encoding="utf-8")
predict1<-predict(lm.step3,newdata=preds,interval="prediction",level=0.95)
exp(predict1)
write.csv(exp(predict1),file="E:/U/viruskillersRound2/predict2.csv",quote=F,row.names = F)